# Generated by Django 5.2.8 on 2025-12-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام برچسب')),
                ('posts', models.ManyToManyField(related_name='tags', to='core.blogpost', verbose_name='پست\u200cها')),
            ],
            options={
                'verbose_name': 'برچسب وبلاگ',
                'verbose_name_plural': 'برچسب\u200cهای وبلاگ',
            },
        ),
    ]
