# Generated by Django 5.2.8 on 2025-12-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_blogtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtag',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='tags', to='core.blogpost', verbose_name='پست\u200cها'),
        ),
    ]
