# Generated by Django 5.2.8 on 2025-12-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_blogcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام دسته\u200cبندی')),
                ('posts', models.ManyToManyField(blank=True, related_name='categories', to='core.blogpost', verbose_name='پست\u200cها')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی وبلاگ',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای وبلاگ',
            },
        ),
    ]
