# Generated by Django 5.2.8 on 2025-12-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_blogcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='counter_view',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید'),
        ),
    ]
