# Generated by Django 6.0 on 2025-12-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_blogcategory_id_alter_blogcomment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
