# Generated by Django 5.2.8 on 2025-12-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام محصول')),
                ('detail', models.CharField(blank=True, max_length=500, null=True, verbose_name='جزئیات محصول')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='products/', verbose_name='تصویر محصول')),
                ('description_image', models.ImageField(blank=True, null=True, upload_to='products/description/', verbose_name='تصویر توضیحات محصول')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='موجودی')),
            ],
        ),
    ]
