# Generated by Django 5.2.8 on 2025-12-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_options_product_discount_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام تگ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('products', models.ManyToManyField(related_name='tags', to='product.product', verbose_name='محصولات')),
            ],
            options={
                'verbose_name': 'تگ محصول',
                'verbose_name_plural': 'تگ های محصولات',
            },
        ),
    ]
