# Generated by Django 5.2.8 on 2025-12-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_producttag_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttag',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='product.product', verbose_name='محصولات'),
        ),
    ]
