# Generated by Django 5.2.8 on 2025-12-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='پیشنهاد ویژه '),
        ),
    ]
