# Generated by Django 5.2.8 on 2025-12-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_remove_producttag_products_product_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='categories', to='product.productcategory', verbose_name='دسته بندی'),
        ),
    ]
