# Generated by Django 6.0 on 2025-12-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_remove_productcategory_products_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default/defaultproduct.jpg', upload_to='products/', verbose_name='تصویر محصول'),
        ),
    ]
