# Generated by Django 6.0 on 2025-12-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(default='default/category_default.jpg', upload_to='products/category_images'),
        ),
    ]
